plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'org.jetbrains.kotlin.plugin.serialization' version '1.9.23'
    alias(libs.plugins.kotlin.compose) // Or match your Kotlin version
}

android {
    compileSdk 36
    defaultConfig {
        applicationId "com.example.kotlindrummachine"
        minSdkVersion 21
        targetSdk 36
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion '1.3.2' // Ensure this is compatible with your Kotlin version
    }
    namespace 'com.example.kotlindrummachine'
}

dependencies {
    implementation libs.androidx.core.ktx.v190
    implementation libs.androidx.lifecycle.runtime.ktx.v262
    implementation libs.androidx.activity.compose.v170
    implementation libs.ui // Check for latest version
    implementation libs.ui.tooling.preview // Check for latest version
    implementation libs.androidx.material // Check for latest version
    implementation libs.kotlinx.serialization.json // Serialization
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit.v115
    androidTestImplementation libs.androidx.espresso.core.v351
    androidTestImplementation libs.ui.test.junit4 // Check for latest version
    debugImplementation libs.ui.tooling // Check for latest version
}
